database/models/produto.py
import sqlite3
import mysql.connector as mysql
from dataclasses import dataclass


@dataclass
class Produto:
    id: int
    codigo: int
    nome: str
    descricao: str
    unidade: str
    quantidade_minima: int
    status: str

    def get_tuple(self):
        return (self.codigo, self.nome, self.descricao, self.unidade, self.quantidade_minima, self.status)

    def __str__(self):
        return self.nome

def create(produto: Produto, cursor: mysql.connection.MySQLCursor):
    try:
        cursor.execute(
            'INSERT INTO produto (codigo, nome, descricao, unidade, quantidade_minima, status) VALUES (%s, %s, %s, %s, %s, %s)',
            produto.get_tuple()
        )
        produto.id = cursor.lastrowid
    except sqlite3.IntegrityError:
        raise Exception('Não é possivel cadastrar produto com código já existente')
    except sqlite3.Error:
        raise Exception('Erro ao cadastrar produto')


def list_all(cursor: mysql.connection.MySQLCursor):
    try:
        cursor.execute('SELECT * FROM produto ORDER BY codigo')
    except sqlite3.Error:
        raise Exception('Erro ao listar produtos')
    
    rows = cursor.fetchall()
    produtos: list[Produto] = []

    for row in rows:
        produtos.append(Produto(*row))

    return produtos


def get(_id, cursor: mysql.connection.MySQLCursor):
    try:
        cursor.execute('SELECT * FROM produto WHERE id = %s', (_id,))
    except sqlite3.Error:
        raise Exception('Erro ao recuperar produto')
    row = cursor.fetchone()

    return Produto(*row) if row else None


def get_by_cod(cod, cursor: mysql.connection.MySQLCursor):
    
    try:
        cursor.execute('SELECT * FROM produto WHERE codigo = %s', (cod,))
    except sqlite3.Error:
        raise Exception('Erro ao recuperar produto')
    row = cursor.fetchone()

    return Produto(*row) if row else None


def update(_id, produto: Produto, cursor: mysql.connection.MySQLCursor):
    try:
        cursor.execute(
            'UPDATE produto SET codigo = %s, nome = %s, descricao = %s, unidade = %s, quantidade_minima = %s, status = %s WHERE id = %s',
            produto.get_tuple() + (_id,)
        )
    except sqlite3.Error:
        raise Exception('Erro ao atualizar produto')


def delete(_id, cursor: mysql.connection.MySQLCursor):
    try:
        cursor.execute(
            'DELETE FROM produto WHERE id = %s',
            (_id,)
        )
    except sqlite3.Error:
        raise Exception('Erro ao deletar produto')

views/routes_produto.py
from flask import Blueprint, render_template, redirect, flash, url_for, request, session
from datetime import date, datetime, timedelta

from database.scripts.db import connect_db
import database.models.produto as prod
import database.models.dias_fechados as dias
import database.models.saldo_diario as saldos
import database.models.entradas as entradas
from database.scripts.utils import login_required

produtos = Blueprint('produtos', __name__)

@produtos.route('/produtos/')
@login_required
def produtos_lista():
    with connect_db() as (conn, cursor):
        produtos_list = prod.list_all(cursor)

    return render_template('produtos.html', produtos=produtos_list)

@produtos.route('/cadastro/produtos/', methods=['POST'])
@login_required
def cadastro_produtos():
    if session['tipo'] not in ['Admin', 'Editor']:
        flash('Permissão negada')
        return redirect(url_for('produtos.produtos_lista'))
    
    codigo = request.form.get('codigo')
    nome = request.form.get('nome')
    descricao = request.form.get('descricao')
    unidade = request.form.get('unidade')
    quantidade_minima = request.form.get('quantidade_minima')
    quantidade_atual = request.form.get('quantidade_atual')
    status = request.form.get('status')

    novo_produto = prod.Produto(0, codigo, nome, descricao, unidade, quantidade_minima, status)
    if not validar_dados(novo_produto, quantidade_atual):
        flash('Insira dados válidos')
        return redirect(url_for('produtos.produtos_lista'))

    try:
        with connect_db() as (conn, cursor):
            prod.create(novo_produto, cursor)

            # Cria a entrada inicial do produto
            data_atual = date.today().isoformat()
            verificar_dia_aberto(data_atual, cursor)

            dia = dias.get(data_atual, cursor)
            if not dia:
                dia = dias.DiasFechados(data_atual, False)
                dias.create(dia, cursor)
            elif dia.fechado:
                raise Exception('Não é possivel cadastrar produtos nesse dia, pois o dia está fechado!')

            saldo_diario = saldos.SaldoDiario(0, novo_produto.id, data_atual, 0, quantidade_atual, 0, quantidade_atual)
            saldos.create(saldo_diario, cursor)
                
            entrada = entradas.Entrada(0, novo_produto.id, data_atual, quantidade_atual, 'Entrada inicial', session['user_id'])
            entradas.create(entrada, cursor)
    except Exception as e:
        flash(f'Falha ao cadastrar produto: {e}')
    else:
        flash('Produto cadastrado com sucesso!')

    return redirect(url_for('produtos.produtos_lista'))

@produtos.route('/editar/produto/<int:produto_id>/', methods=['POST'])
@login_required
def editar_produto(produto_id):
    if session['tipo'] not in ['Admin', 'Editor']:
        flash('Permissão negada')
        return redirect(url_for('produtos.produtos_lista'))
    
    try:
        with connect_db() as (conn, cursor):
            produto = prod.get(produto_id, cursor)
            produto.codigo = request.form.get('edit_codigo')
            produto.nome = request.form.get('edit_nome')
            produto.descricao = request.form.get('edit_descricao')
            produto.unidade = request.form.get('edit_unidade')
            produto.quantidade_minima = request.form.get('edit_quantidade_minima')
            produto.status = request.form.get('edit_status')

            if not validar_dados(produto, 0):
                flash('Insira dados válidos')
                return redirect(url_for('produtos.produtos_lista'))

            prod.update(produto_id, produto, cursor)
    except Exception as e:
        flash(f'Falha ao atualizar produto: {e}')
    else:
        flash('Produto atualizado com sucesso!')

    return redirect(url_for('produtos.produtos_lista'))


@produtos.route('/excluir/produto/<int:produto_id>/', methods=['POST'])
@login_required
def excluir_produto(produto_id):
    if session['tipo'] not in ['Admin', 'Editor']:
        flash('Permissão negada')
        return redirect(url_for('produtos.produtos_lista'))
    
    try:
        with connect_db() as (conn, cursor):
            prod.delete(produto_id, cursor)
    except Exception as e:
        flash(f'Falha ao deletar produto: {e}')
    else:
        flash('Produto deletado com sucesso!')

    return redirect(url_for('produtos.produtos_lista'))


def validar_dados(produto: prod.Produto, quantidade_atual):
    if produto.codigo == '' or produto.nome == '' or produto.quantidade_minima == '' or produto.status == '' or quantidade_atual == '':
        return False
    
    try:
        codigo = int(produto.codigo)
        quantidade_minima = int(produto.quantidade_minima)
        quantidade_atual = int(quantidade_atual)
    except (ValueError, TypeError):
        return False

    if codigo < 0 or quantidade_minima <= 0 or quantidade_atual < 0:
        return False
    
    if produto.status not in ['Disponivel', 'Não disponivel']:
        return False
    
    return True

def verificar_dia_aberto(data: str, cursor):
    mais_recente = dias.get_open_day(cursor)
    if mais_recente == None:
        return
    
    data_mais_recente = datetime.strptime(mais_recente.data, '%Y-%m-%d').date()
    data = datetime.strptime(data, '%Y-%m-%d').date()
    saldos_diarios = saldos.list_by_date(data_mais_recente.isoformat(), cursor)

    if data_mais_recente == data:
        return

    if data_mais_recente < data:
        mais_recente.fechado = True
        dias.update(mais_recente.data, mais_recente, cursor)

        while data_mais_recente < data:
            data_mais_recente += timedelta(days=1)

            for saldo in saldos_diarios:
                s = saldos.SaldoDiario(0, saldo.produto_id, data_mais_recente.isoformat(), saldo.quantidade_final, 0, 0, saldo.quantidade_final)
                saldos.create(s, cursor)
            
            if data_mais_recente == data:
                fechado = False
            else:
                fechado = True
            dia = dias.DiasFechados(data_mais_recente.isoformat(), fechado)
            dias.create(dia, cursor)

  

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estoque IFCE - Crato</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">IFCE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        {% if 'user_id' not in session %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/login">Login</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/logout">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul id="messages" class="list-unstyled">
            {% for message in messages %}
                <li class="alert {{ 'alert-success' if 'sucesso' in message else 'alert-danger' }}">{{ message }}</li>
            {% endfor %}
        </ul>
        <script>
            setTimeout(function() {
                const messageBox = document.getElementById('messages');
                if (messageBox) {
                    messageBox.style.display = 'none';
                }
            }, 5000); 
        </script>
    {% endif %}
{% endwith %}

    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

{% if 'nome' in session.keys() %}
    <h2>Olá {{ session.get('nome') }}</h2>
{% endif %}

<ul>
    <li><a href="{{ url_for('produtos.produtos_lista') }}">Produtos</a></li>
    <li><a href="{{ url_for('movimentacoes_diarias', data=None) }}">Movimentações diárias</a></li>
</ul>

<h2>Dia aberto: {{ dia.data }}</h2>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<form action="/login" method="POST">
  <div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <input type="email" class="form-control" id="email" name="email">
  </div>
  <div class="mb-3">
    <label for="password" class="form-label">Senha</label>
    <input type="password" class="form-control" id="password" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Enviar</button>
</form>

{% endblock %}

templates/produtos.html
{% extends 'base.html' %}

{% block content %}

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#cadastroProdutoModal">
    Cadastrar novo produto
</button>

<div class="modal fade" id="cadastroProdutoModal" tabindex="-1" aria-labelledby="cadastroProdutoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <form action="{{ url_for('produtos.cadastro_produtos') }}" method="POST">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="cadastroProdutoModalLabel">Cadastrar Produto</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="mb-3">
                <label for="codigo" class="form-label">Código</label>
                <input id="codigo" name="codigo" type="number" class="form-control" required>
            </div>
            
            <div class="mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input id="nome" name="nome" type="text" class="form-control" required>
            </div>
            
            <div class="mb-3">
                <label for="descricao" class="form-label">Descrição</label>
                <input id="descricao" name="descricao" type="text" class="form-control">
            </div>

            <div class="mb-3">
                <label for="unidade" class="form-label">Unidade</label>
                <input id="unidade" name="unidade" type="text" class="form-control" required>
            </div>
            
            <div class="mb-3">
                <label for="quantidade_minima" class="form-label">Quantidade minima</label>
                <input id="quantidade_minima" name="quantidade_minima" type="number" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="quantidade_atual" class="form-label">Quantidade atual</label>
                <input id="quantidade_atual" name="quantidade_atual" type="number" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="status" class="form-label">Status</label>
                <select id="status" name="status" class="form-select">
                    {% for destino in ['Disponivel', 'Não disponivel'] %}
                        <option value="{{ destino }}">{{ destino }}</option>
                    {% else %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
    <div class="table-responsive">

        <table class="table table-striped table-bordered table-hover">
        <thead class="table-dark">
            <tr>
                <th scope="col">Código</th>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
                <th scope="col">Unidade</th>
                <th scope="col">Quantidade minima</th>
                <th scope="col">Status</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        
        <tbody>

            {% for produto in produtos %}
                <tr>
                    <td scope="row">{{ produto.codigo }}</td>
                    <td>{{ produto.nome }}</td>
                    <td>{{ produto.descricao }}</td>
                    <td>{{ produto.unidade }}</td>
                    <td>{{ produto.quantidade_minima }}</td>
                    <td>{{ produto.status }}</td>
                    <td>
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editProdutoModal" onclick="fillEditForm('{{produto.id}}', '{{produto.codigo}}', '{{produto.nome}}', '{{produto.descricao}}', '{{produto.unidade}}', '{{produto.quantidade_minima}}', '{{produto.status}}')">Editar</button>
                        {% if session.get('tipo') == 'Admin' %}
                        <form action="{{ url_for('produtos.excluir_produto', produto_id=produto.id) }}" method="POST" onsubmit="return confirm('Tem certeza que deseja excluir este produto?')">
                            <button type="submit" class="btn btn-danger">Excluir</button>
                        </form>
                        {% endif %}
                    </td>
            </tr>
            {% else %}
                <p>Ainda não há produtos cadastrados</p>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>


<div class="modal fade" id="editProdutoModal" tabindex="-1" aria-labelledby="editProdutoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <form id="editProdutoForm" method="POST">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editProdutoModalLabel">Editar Produto</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="mb-3">
                <label for="edit_codigo" class="form-label">Código</label>
                <input id="edit_codigo" name="edit_codigo" type="text" class="form-control" readonly>
            </div>
            
            <div class="mb-3">
                <label for="edit_nome" class="form-label">Nome</label>
                <input id="edit_nome" name="edit_nome" type="text" class="form-control">
            </div>
            
            <div class="mb-3">
                <label for="edit_descricao" class="form-label">Descrição</label>
                <input id="edit_descricao" name="edit_descricao" type="text" class="form-control">
            </div>

            <div class="mb-3">
                <label for="edit_unidade" class="form-label">Unidade</label>
                <input id="edit_unidade" name="edit_unidade" type="text" class="form-control">
            </div>
            
            <div class="mb-3">
                <label for="edit_quantidade_minima" class="form-label">Quantidade minima</label>
                <input id="edit_quantidade_minima" name="edit_quantidade_minima" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label for="edit_status" class="form-label">Status</label>
                <select id="edit_status" name="edit_status" class="form-select">
                    {% for destino in ['Disponivel', 'Não disponivel'] %}
                        <option value="{{ destino }}">{{ destino }}</option>
                    {% else %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">Editar</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
    function fillEditForm(id, codigo, nome, descricao, unidade, quantidade_minima, status) {
        document.getElementById("edit_codigo").value = codigo;
        document.getElementById("edit_nome").value = nome;
        document.getElementById("edit_descricao").value = descricao;
        document.getElementById("edit_unidade").value = unidade;
        document.getElementById("edit_quantidade_minima").value = quantidade_minima;
        document.getElementById("edit_status").value = status;

        document.getElementById("editProdutoForm").action = "{{ url_for('produtos.editar_produto', produto_id=0) }}".replace('0', id);
    }
</script>

    
{% endblock %}